Carson/handle errors
infinyon/http-source-connector pull request #154
Opened 2024-02-08 04:06 UTC by crajcan

2024-02-08 20:04 UTC, digikata requested changes
Looks good overall, some minor input on visibility of reconnects.

2024-02-08 20:04 UTC, digikata commented on crates/http-source/src/main.rs
> +                    continue;
Not sure the best place to put it, but there should be a way for a user to see and assess reconnects in the regular logs.  I think a `warn` or `error` log output on disconnect, and an `info` on successful connect would be sufficient for that.

2024-02-08 21:07 UTC, digikata approved these changes
Nice, thanks for the update!

2024-02-08 21:14 UTC, merged

2024-02-09 14:10 UTC, ajhunyady reviewed
does this update require a patch number change?
how can I tell if it's in the build and ready to test?

2024-02-09 14:25 UTC, crajcan commented
> does this update require a patch number change?
> 
> how can I tell if it's in the build and ready to test?

It has been merged but not released. I'm not quite sure what the procedure is, it looks like Alex has done the last few.

2024-02-09 14:28 UTC, ajhunyady commented
@digikata we may need a `checklist` doc with instructions on how to release a connector.

2024-02-09 16:28 UTC, digikata commented
For this connector the procedure to push a tag to the repository that is formatted `vX.Y.Z`

2024-02-09 17:05 UTC, digikata commented
I added a release instruction template.  @crajcan Can you try it out and see if it makes sense to you?